-- USING THE DATA WAREHOUSE NAMED AS FLATTEN_WAREHOUSE
USE WAREHOUSE FLATTEN_WAREHOUSE;

-- USING THE DATABASES NAMED AS FLATTEN_DATABASE
USE DATABASE FLATTEN_DATABASE;

-- CREATING AND USING THE SCHEMA NAMED AS FLATTEN_SCHEMA
CREATE 
OR REPLACE SCHEMA FLATTEN_PARQUET_SCHEMA;
USE SCHEMA FLATTEN_PARQUET_SCHEMA;

--CREATING THE STAGE NAMED AS STORE_STAGE 
CREATE 
OR REPLACE STAGE PARQUET_STAGE COPY_OPTIONS =(on_error = 'skip_file');

-- SHOWING THE LIST OF STAGES
SHOW STAGES;

-- SHOWING THE FILES IN THE STAGES NAMED AS PARQUET_STAGE
LIST @PARQUET_STAGE;
----PUT FILE://Fuse/snowfalke/snowsql_project/datas/parquet_flatten_userdata.parquet @PARQUET_STAGE;


--CREATE A TABLE WITH A SINGLE VARIENT COLUMN NAMED AS USER_DATA
CREATE
OR REPLACE TABLE "FLATTEN_DATABASE"."FLATTEN_PARQUET_SCHEMA"."PARQUET_USER_TABLE"(
     USER_DATA VARIANT NOT NULL
);                                                      
-- copying the data from stage to the table
COPY INTO "FLATTEN_DATABASE"."FLATTEN_PARQUET_SCHEMA"."PARQUET_USER_TABLE"
FROM @parquet_stage/parquet_flatten_userdata.parquet   
FILE_FORMAT=(TYPE=PARQUET) 
ON_ERROR='CONTINUE';


--Query the relational table                                                                                 */
SELECT * FROM "FLATTEN_DATABASE"."FLATTEN_PARQUET_SCHEMA"."PARQUET_USER_TABLE";

SELECT $1:birthdate FROM "FLATTEN_DATABASE"."FLATTEN_PARQUET_SCHEMA"."PARQUET_USER_TABLE";



CREATE
OR REPLACE TABLE "FLATTEN_DATABASE"."FLATTEN_PARQUET_SCHEMA"."USER_TABLE"(
  "ID" INTEGER,
  "FIRST_NAME" STRING,
  "LAST_NAME" STRING,
  "GENDER" STRING,
  "SALARY" FLOAT,
  "TITLE" STRING,
  "BIRTH_DATE" STRING,
  "EMAIL" STRING,
  "COUNTRY" STRING,
  "IP_ADDRESS" STRING,
  "COMMETNS" STRING,
  "CC" STRING,
  "REGISTRATION_DATE_TIME"STRING
);

-- INSERTING THE VALUE FROM PQRQUET_USER_TABLE TABLE TO USER_TABLE TABLE
INSERT INTO  "FLATTEN_DATABASE"."FLATTEN_PARQUET_SCHEMA"."USER_TABLE"
SELECT
    $1:id,$1:first_name,$1:last_name,
    $1:gender,$1:salary,$1:title,
    $1:birthdate,$1:email,
    $1:country,$1:ip_address,
    $1:comments,$1:cc,$1:registration_dttm
FROM "FLATTEN_DATABASE"."FLATTEN_PARQUET_SCHEMA"."PARQUET_USER_TABLE";

SELECT
  *
FROM "FLATTEN_DATABASE"."FLATTEN_PARQUET_SCHEMA"."USER_TABLE"; 
